# Generated by Django 6.0.3 on 2026-03-25 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_type', models.TextField()),
                ('act_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
                'db_table': 'act',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_scope', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('delivery_status', models.TextField()),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'db_table': 'delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_pasport_number', models.CharField(max_length=50, unique=True)),
                ('employee_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_post', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('expenditure_id', models.AutoField(primary_key=True, serialize=False)),
                ('expenditure_scope_id', models.IntegerField(blank=True, null=True)),
                ('expenditure_data', models.DateField()),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'db_table': 'expenditure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('wood_id', models.AutoField(primary_key=True, serialize=False)),
                ('wood_type', models.CharField(blank=True, max_length=100, null=True)),
                ('wood_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('wood_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wood_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wood_the_upper_end_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wood_lower_end_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wood_graduation', models.CharField(blank=True, max_length=50, null=True)),
                ('wood_cross_section', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuppliersContract',
            fields=[
                ('suppliers_contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=100)),
                ('suppliers_contract_status', models.TextField()),
                ('suppliers_contract_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('suppliers_contract_scope', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suppliers_contract_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Контракт поставщика',
                'verbose_name_plural': 'Контракты поставщиков',
                'db_table': 'suppliers_contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuppliersInfo',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_address', models.TextField(blank=True, null=True)),
                ('supplier_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('supplier_inn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'suppliers_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierWood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Материал поставщика',
                'verbose_name_plural': 'Материалы поставщиков',
                'db_table': 'supplier_wood',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'db_table': 'user_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_login', models.CharField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('wood', models.OneToOneField(db_column='wood_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.product')),
                ('current_scope', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_cell', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
                'db_table': 'storage',
                'managed': False,
            },
        ),
    ]
